// Mock database containing 25+ premium movies across categories to represent the TMDB API database
export const mockMovies = [
  // NETFLIX ORIGINALS (Vertical Layout primarily)
  {
    id: 101,
    title: "Stranger Chronicles",
    name: "Stranger Chronicles",
    backdrop_path: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80",
    poster_path: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=600&q=80",
    overview: "When a young boy vanishes from a small Indiana town, his friends uncover a web of secret government exploits, supernatural forces, and one very strange little girl with telekinetic powers.",
    vote_average: 8.8,
    release_date: "2024-07-15",
    first_air_date: "2024-07-15",
    match_percentage: 98,
    duration: "4 Seasons",
    maturity_rating: "TV-14",
    genres: ["Sci-Fi", "Drama", "Mystery"],
    category: "originals",
    isOriginal: true,
  },
  {
    id: 102,
    title: "Cyber Edge: 2099",
    name: "Cyber Edge: 2099",
    backdrop_path: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80",
    poster_path: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&w=600&q=80",
    overview: "In a neon-drenched dystopian metropolis, a street-smart mercenary fighting for survival becomes entangled with a mysterious artificial intelligence that could change humanity forever.",
    vote_average: 8.6,
    release_date: "2025-02-10",
    first_air_date: "2025-02-10",
    match_percentage: 95,
    duration: "2 Seasons",
    maturity_rating: "TV-MA",
    genres: ["Action", "Sci-Fi", "Cyberpunk"],
    category: "originals",
    isOriginal: true,
  },
  {
    id: 103,
    title: "The Royal Reign",
    name: "The Royal Reign",
    backdrop_path: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=1200&q=80",
    poster_path: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=600&q=80",
    overview: "Based on historical events, this drama follows the political rivalries, personal romances, and complex power struggles during the long and tumultuous reign of Queen Elizabeth II.",
    vote_average: 8.9,
    release_date: "2023-11-04",
    first_air_date: "2023-11-04",
    match_percentage: 92,
    duration: "6 Seasons",
    maturity_rating: "TV-MA",
    genres: ["Drama", "History", "Biography"],
    category: "originals",
    isOriginal: true,
  },
  {
    id: 104,
    title: "Shadow Syndicate",
    name: "Shadow Syndicate",
    backdrop_path: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=1200&q=80",
    poster_path: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=600&q=80",
    overview: "An elite band of international thieves orchestrate the ultimate heist: infiltrating the world's most secure royal mint using an elaborate set of rules and psychological chess.",
    vote_average: 8.5,
    release_date: "2024-04-18",
    first_air_date: "2024-04-18",
    match_percentage: 94,
    duration: "5 Parts",
    maturity_rating: "TV-MA",
    genres: ["Action", "Crime", "Thriller"],
    category: "originals",
    isOriginal: true,
  },
  {
    id: 105,
    title: "Wednesday's Curse",
    name: "Wednesday's Curse",
    backdrop_path: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    poster_path: "https://images.unsplash.com/photo-1618336753974-aae8e04506aa?auto=format&fit=crop&w=600&q=80",
    overview: "Smart, sarcastic and a little dead inside, Wednesday Addams investigates a murder spree while making new friends — and foes — at Nevermore Academy.",
    vote_average: 8.4,
    release_date: "2023-11-23",
    first_air_date: "2023-11-23",
    match_percentage: 97,
    duration: "1 Season",
    maturity_rating: "TV-14",
    genres: ["Comedy", "Fantasy", "Mystery"],
    category: "originals",
    isOriginal: true,
  },

  // TRENDING NOW (Landscape primarily)
  {
    id: 201,
    title: "Interstellar Abyss",
    backdrop_path: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
    poster_path: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=600&q=80",
    overview: "A team of explorers travel beyond this galaxy through a newly discovered wormhole in an attempt to ensure humanity's survival on a dying, dust-choked Earth.",
    vote_average: 8.7,
    release_date: "2024-11-07",
    match_percentage: 99,
    duration: "2h 49m",
    maturity_rating: "PG-13",
    genres: ["Sci-Fi", "Adventure", "Drama"],
    category: "trending",
  },
  {
    id: 202,
    title: "Apex Predator",
    backdrop_path: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
    poster_path: "https://images.unsplash.com/photo-1608889175123-8ee362201f81?auto=format&fit=crop&w=600&q=80",
    overview: "An undercover cop finds himself drawn into the high-adrenaline world of illegal street racing, led by a charismatic driver with a strong sense of family loyalty.",
    vote_average: 7.8,
    release_date: "2025-01-22",
    match_percentage: 89,
    duration: "1h 46m",
    maturity_rating: "PG-13",
    genres: ["Action", "Crime", "Thriller"],
    category: "trending",
  },
  {
    id: 203,
    title: "The Great Heist of Tokyo",
    backdrop_path: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1200&q=80",
    poster_path: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=600&q=80",
    overview: "A mastermind and his crew of code-named thieves lock themselves inside the Tokyo central bank with hostages, planning to print trillions of Yen while playing mind games with the police.",
    vote_average: 8.2,
    release_date: "2024-09-30",
    match_percentage: 91,
    duration: "2h 15m",
    maturity_rating: "R",
    genres: ["Crime", "Thriller", "Action"],
    category: "trending",
  },
  {
    id: 204,
    title: "Chrono-Quest",
    backdrop_path: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=1200&q=80",
    poster_path: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
    overview: "A time-traveling fighter pilot accidentally crash-lands in 2024 and teams up with his 12-year-old self on a mission to save the future from an existential threat.",
    vote_average: 7.9,
    release_date: "2025-03-05",
    match_percentage: 88,
    duration: "1h 50m",
    maturity_rating: "PG",
    genres: ["Adventure", "Sci-Fi", "Comedy"],
    category: "trending",
  },

  // TOP RATED
  {
    id: 301,
    title: "The Redemption Code",
    backdrop_path: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    poster_path: "https://images.unsplash.com/photo-1505686994434-e3cc5abf1330?auto=format&fit=crop&w=600&q=80",
    overview: "Framed for a brutal crime he didn't commit, a banker forms a deep, decades-long friendship with a fellow inmate while secretly plotting a brilliant escape.",
    vote_average: 9.3,
    release_date: "1994-09-23",
    match_percentage: 99,
    duration: "2h 22m",
    maturity_rating: "R",
    genres: ["Drama", "Crime"],
    category: "topRated",
  },
  {
    id: 302,
    title: "The Cyber Knight",
    backdrop_path: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=80",
    poster_path: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=600&q=80",
    overview: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    vote_average: 9.0,
    release_date: "2008-07-18",
    match_percentage: 97,
    duration: "2h 32m",
    maturity_rating: "PG-13",
    genres: ["Action", "Crime", "Drama"],
    category: "topRated",
  },
  {
    id: 303,
    title: "Inception Horizon",
    backdrop_path: "https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?auto=format&fit=crop&w=1200&q=80",
    poster_path: "https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?auto=format&fit=crop&w=600&q=80",
    overview: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    vote_average: 8.8,
    release_date: "2010-07-16",
    match_percentage: 96,
    duration: "2h 28m",
    maturity_rating: "PG-13",
    genres: ["Action", "Sci-Fi", "Adventure"],
    category: "topRated",
  },

  // ACTION MOVIES
  {
    id: 401,
    title: "Velocity Shift",
    backdrop_path: "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1200&q=80",
    poster_path: "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=600&q=80",
    overview: "A highly skilled tactical driver must race against the clock to deliver a vital package through a hostile territory filled with corrupt mercenaries.",
    vote_average: 7.5,
    release_date: "2023-05-12",
    match_percentage: 86,
    duration: "1h 58m",
    maturity_rating: "R",
    genres: ["Action", "Thriller"],
    category: "action",
  },
  {
    id: 402,
    title: "Shadow Warrior",
    backdrop_path: "https://images.unsplash.com/photo-1533928298208-27ff66555d8d?auto=format&fit=crop&w=1200&q=80",
    poster_path: "https://images.unsplash.com/photo-1533928298208-27ff66555d8d?auto=format&fit=crop&w=600&q=80",
    overview: "An assassin seeking retirement is suddenly hunted by a younger, stronger clone of himself who knows his every move before he makes it.",
    vote_average: 7.2,
    release_date: "2022-10-11",
    match_percentage: 83,
    duration: "1h 52m",
    maturity_rating: "PG-13",
    genres: ["Action", "Sci-Fi", "Thriller"],
    category: "action",
  },
  {
    id: 403,
    title: "Gladiator Reborn",
    backdrop_path: "https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?auto=format&fit=crop&w=1200&q=80",
    poster_path: "https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?auto=format&fit=crop&w=600&q=80",
    overview: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    vote_average: 8.5,
    release_date: "2000-05-05",
    match_percentage: 95,
    duration: "2h 35m",
    maturity_rating: "R",
    genres: ["Action", "Adventure", "Drama"],
    category: "action",
  },

  // COMEDY MOVIES
  {
    id: 501,
    title: "The Ultimate Hangout",
    backdrop_path: "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=1200&q=80",
    poster_path: "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=600&q=80",
    overview: "Three best friends throw a wild house party that spins out of control, leading to a series of hilarious and disastrous misunderstandings with neighbors and local authorities.",
    vote_average: 7.1,
    release_date: "2024-06-18",
    match_percentage: 84,
    duration: "1h 38m",
    maturity_rating: "R",
    genres: ["Comedy"],
    category: "comedy",
  },
  {
    id: 502,
    title: "Dumb & Dumber Clones",
    backdrop_path: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?auto=format&fit=crop&w=1200&q=80",
    poster_path: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?auto=format&fit=crop&w=600&q=80",
    overview: "After a scientific experiment goes completely wrong, a pair of incredibly simple-minded friends are accidentally cloned, doubling the trouble and the laughs.",
    vote_average: 6.8,
    release_date: "2023-12-25",
    match_percentage: 80,
    duration: "1h 42m",
    maturity_rating: "PG",
    genres: ["Comedy", "Sci-Fi"],
    category: "comedy",
  },
  {
    id: 503,
    title: "Office Catastrophe",
    backdrop_path: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
    poster_path: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=600&q=80",
    overview: "When a dry corporate consultant attempts to restructure a quirky start-up office, the employees band together to pull off the ultimate, hilarious workplace revolt.",
    vote_average: 7.4,
    release_date: "2024-03-01",
    match_percentage: 85,
    duration: "1h 40m",
    maturity_rating: "PG-13",
    genres: ["Comedy", "Romance"],
    category: "comedy",
  },

  // HORROR MOVIES
  {
    id: 601,
    title: "The Haunted Asylum",
    backdrop_path: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=1200&q=80",
    poster_path: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=600&q=80",
    overview: "A team of paranormal investigators trap themselves in an abandoned asylum overnight to record proof of the supernatural, only to realize the spirits are very real and hostile.",
    vote_average: 7.0,
    release_date: "2023-10-31",
    match_percentage: 82,
    duration: "1h 36m",
    maturity_rating: "R",
    genres: ["Horror", "Mystery", "Thriller"],
    category: "horror",
  },
  {
    id: 602,
    title: "Cabin In The Woods",
    backdrop_path: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=1200&q=80",
    poster_path: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80",
    overview: "Five teenagers go to a remote cabin in the woods, where they get more than they bargained for, discovering the truth behind the cabin's dark and mystical history.",
    vote_average: 7.3,
    release_date: "2012-04-13",
    match_percentage: 87,
    duration: "1h 35m",
    maturity_rating: "R",
    genres: ["Horror", "Sci-Fi", "Comedy"],
    category: "horror",
  },
  {
    id: 603,
    title: "The Whisperer",
    backdrop_path: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    poster_path: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=600&q=80",
    overview: "A deaf writer who retreated into the woods to live a solitary life must fight for her life in silence when a masked killer appears at her window.",
    vote_average: 6.9,
    release_date: "2016-03-12",
    match_percentage: 78,
    duration: "1h 21m",
    maturity_rating: "R",
    genres: ["Horror", "Thriller"],
    category: "horror",
  },

  // DOCUMENTARIES
  {
    id: 701,
    title: "Planet Wilderness",
    backdrop_path: "https://images.unsplash.com/photo-1546182990-dffeafbe841d?auto=format&fit=crop&w=1200&q=80",
    poster_path: "https://images.unsplash.com/photo-1546182990-dffeafbe841d?auto=format&fit=crop&w=600&q=80",
    overview: "Embark on an immersive, high-definition journey across our globe to witness the marvels of animal behavior and the breathtaking ecosystems of the wild.",
    vote_average: 9.1,
    release_date: "2024-01-01",
    match_percentage: 96,
    duration: "1 Season",
    maturity_rating: "TV-G",
    genres: ["Documentary", "Nature", "Science"],
    category: "documentary",
  },
  {
    id: 702,
    title: "Formula: Speed & Fury",
    backdrop_path: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80",
    poster_path: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=600&q=80",
    overview: "Drivers, managers and team owners live life in the fast lane — both on and off the track. Get unparalleled access to the high-stakes world of Formula racing.",
    vote_average: 8.6,
    release_date: "2023-03-08",
    match_percentage: 91,
    duration: "5 Seasons",
    maturity_rating: "TV-MA",
    genres: ["Documentary", "Sports", "Drama"],
    category: "documentary",
  },
  {
    id: 703,
    title: "The Silicon Boom",
    backdrop_path: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
    poster_path: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80",
    overview: "An investigative documentary exploring the hyper-accelerated rise of Artificial Intelligence, from the silicon labs of California to its global impact on human society.",
    vote_average: 8.0,
    release_date: "2025-05-10",
    match_percentage: 93,
    duration: "1h 48m",
    maturity_rating: "TV-PG",
    genres: ["Documentary", "Science", "Tech"],
    category: "documentary",
  }
];

// Add recommendations / similar movies for each movie by linking similar category movies
mockMovies.forEach(movie => {
  movie.similar_movies = mockMovies
    .filter(m => m.id !== movie.id && (m.category === movie.category || m.genres.some(g => movie.genres.includes(g))))
    .slice(0, 6) // limit to 6 similar movies
    .map(m => ({
      id: m.id,
      title: m.title || m.name,
      backdrop_path: m.backdrop_path,
      poster_path: m.poster_path,
      vote_average: m.vote_average,
      release_date: m.release_date || m.first_air_date,
      match_percentage: m.match_percentage,
      duration: m.duration,
      maturity_rating: m.maturity_rating,
      overview: m.overview
    }));
});
